const Allproducts = [
  {
    id: 1,
    name: "赫本風蝴蝶結鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_47.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_48.jpg"),
    ],
    category: "clip",
    colors: ["黑色"],
    price: "49",
  },
  {
    id: 2,
    name: "S925純銀蝴蝶結耳環",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_15.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_16.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_17.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_18.jpg"),
    ],
    category: "earring",
    colors: ["銀色", "金色"],
    price: "239",
  },
  {
    id: 3,
    name: "S925純銀人魚尾巴項鍊",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_3.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_1.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_2.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_4.jpg"),
    ],
    category: "necklace",
    colors: ["銀色"],
    price: "239",
  },
  {
    id: 4,
    name: "S925純銀兩戴雙層戒指",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_52.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_53.jpg"),
    ],
    category: "ring",
    colors: ["銀色"],
    price: "119",
  },
  {
    id: 5,
    name: "S925純銀貓眼愛心耳環",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_7.jfif"),
      require("../picture/products/LINE_ALBUM_商品照_240530_8.jpg"),
    ],

    category: "earring",
    colors: ["銀色"],
    price: "89",
  },
  {
    id: 6,
    name: "S925純銀兩戴貝母愛心耳環",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_11.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_9.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_10.jpg"),
    ],
    category: "earring",
    colors: ["金色"],
    price: "129",
  },
  {
    id: 7,
    name: "S925純銀簡約小鑽花朵耳環",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_14.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_13.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_12.jpg"),
    ],
    category: "earring",
    colors: ["銀色"],
    price: "119",
  },
  {
    id: 8,
    name: "韓國可愛笑臉大腸髮圈",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_22.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_19.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_20.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_21.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_22.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_23.jpg"),
    ],
    category: "hair",
    colors: ["黑色", "卡其色", "咖啡色", "白色"],
    price: "29",
  },
  {
    id: 9,
    name: "磨砂經典愛心鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_24.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_25.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_26.jpg"),
    ],
    category: "clip",
    colors: ["黑色", "咖啡色"],
    price: "69",
  },
  {
    id: 10,
    name: "素色馬卡龍大腸髮圈",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_27.jfif"),
      require("../picture/products/LINE_ALBUM_商品照_240530_28.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_29.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_30.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_31.jpg"),
    ],
    image: require("../picture/products/LINE_ALBUM_商品照_240530_27.jfif"),
    category: "hair",
    colors: ["紫色", "淺紫色", "水藍色", "黃色", "粉色"],
    price: "19",
  },
  {
    id: 11,
    name: "緞面大蝴蝶結鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_32.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_33.jpg"),
    ],
    category: "hair",
    colors: ["黑色"],
    price: "69",
  },
  {
    id: 12,
    name: "氣質珍珠線條鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_36.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_35.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_37.jpg"),
    ],
    category: "hair",
    colors: ["金色", "咖啡色"],
    price: "79",
  },
  {
    id: 13,
    name: "氣質俐落玫瑰鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_38.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_39.jpg"),
    ],
    category: "hair",
    colors: ["銀色"],
    price: "69",
  },
  {
    id: 14,
    name: "氣質俐落玫瑰鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_40.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_41.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_42.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_43.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_44.jpg"),
    ],
    category: "hair",
    colors: ["米色", "咖啡色"],
    price: "59",
  },
  {
    id: 15,
    name: "透明花朵造型小鯊魚夾",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_45.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_46.jpg"),
    ],
    category: "hair",
    colors: ["白色"],
    price: "29",
  },
  {
    id: 16,
    name: "S925純銀愛心個性戒指",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_50.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_51.jpg"),
    ],
    category: "ring",
    colors: ["銀色"],
    price: "199",
  },

  {
    id: 17,
    name: "S925純銀兩戴貝母愛心耳環",
    images: [
      require("../picture/products/LINE_ALBUM_商品照_240530_5.jpg"),
      require("../picture/products/LINE_ALBUM_商品照_240530_6.jpg"),
    ],
    category: "earring",
    colors: ["銀色"],
    price: "129",
  },
];

export default Allproducts;
