const Allproducts = [
  {
    id: 1,
    name: "赫本風氣質蝴蝶結鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_47.jpg"),
    category: "clip",
    colors: ["黑色"],
    price: "49",
  },
  {
    id: 2,
    name: "S925純銀優雅蝴蝶結耳環",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_15.jpg"),
    category: "earring",
    colors: ["銀色", "金色"],
    price: "239",
  },
  {
    id: 3,
    name: "S925純銀人魚尾巴珍珠項鍊",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_3.jpg"),
    category: "necklace",
    colors: ["銀色"],
    price: "239",
  },
  {
    id: 4,
    name: "S925純銀兩戴貝母愛心耳環",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_5.jpg"),
    category: "earring",
    colors: ["銀色"],
    price: "129",
  },
  {
    id: 5,
    name: "S925純銀貓眼愛心耳環",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_7.jfif"),
    category: "earring",
    colors: ["銀色"],
    price: "89",
  },
  {
    id: 6,
    name: "S925純銀兩戴貝母愛心耳環",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_11.jpg"),
    category: "earring",
    colors: ["金色"],
    price: "129",
  },
  {
    id: 7,
    name: "S925純銀簡約小鑽花朵耳環",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_12.jpg"),
    category: "earring",
    colors: ["銀色"],
    price: "119",
  },
  {
    id: 8,
    name: "韓國可愛笑臉大腸髮圈",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_22.jpg"),
    category: "hair",
    colors: ["黑色", "卡其色", "咖啡色", "白色"],
    price: "29",
  },
  {
    id: 9,
    name: "磨砂經典愛心鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_24.jpg"),
    category: "clip",
    colors: ["黑色", "咖啡色"],
    price: "69",
  },
  {
    id: 10,
    name: "素色馬卡龍大腸髮圈",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_27.jfif"),
    category: "hair",
    colors: ["紫色", "淺紫色", "水藍色", "黃色", "粉色"],
    price: "19",
  },
  {
    id: 11,
    name: "緞面大蝴蝶結鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_32.jpg"),
    category: "hair",
    colors: ["黑色"],
    price: "69",
  },
  {
    id: 12,
    name: "氣質珍珠線條鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_36.jpg"),
    category: "hair",
    colors: ["金色", "咖啡色"],
    price: "79",
  },
  {
    id: 13,
    name: "氣質俐落玫瑰鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_38.jpg"),
    category: "hair",
    colors: ["銀色"],
    price: "69",
  },
  {
    id: 14,
    name: "氣質俐落玫瑰鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_40.jpg"),
    category: "hair",
    colors: ["米色", "咖啡色"],
    price: "59",
  },
  {
    id: 15,
    name: "透明花朵造型小鯊魚夾",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_45.jpg"),
    category: "hair",
    colors: ["白色"],
    price: "29",
  },
  {
    id: 16,
    name: "S925純銀愛心個性戒指",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_50.jpg"),
    category: "ring",
    colors: ["銀色"],
    price: "199",
  },
  {
    id: 17,
    name: "S925純銀兩戴雙層戒指",
    image: require("../picture/products/LINE_ALBUM_商品照_240530_52.jpg"),
    category: "ring",
    colors: ["銀色"],
    price: "119",
  },
];

export default Allproducts;
